default_agent: agentcoreconfluence_agent
agents:
  agentcoreconfluence_agent:
    name: agentcoreconfluence_agent
    language: python
    node_version: null
    entrypoint: /home/javiator/work/projects/learning/confluence-mcp/src/confluence_mcp.chat_appcore_runtime/docker_agent/agentcoreconfluence/src/main.py
    deployment_type: container
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /home/javiator/work/projects/learning/confluence-mcp/src/confluence_mcp.chat_appcore_runtime/docker_agent/agentcoreconfluence
    aws:
      execution_role: arn:aws:iam::383226947124:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-7d4a9db68c
      execution_role_auto_create: false
      account: '383226947124'
      region: us-east-1
      ecr_repository: 383226947124.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcoreconfluence_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcoreconfluence_agent-TpNYJW6yK2
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:383226947124:runtime/agentcoreconfluence_agent-TpNYJW6yK2
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcoreconfluence_agent-builder
      execution_role: arn:aws:iam::383226947124:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-d2e0ea7bf8
      source_bucket: bedrock-agentcore-codebuild-sources-383226947124-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
